SGL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views
from .views import registrar_paciente, editar_paciente, eliminar_paciente

urlpatterns = [
    path('', views.login_view, name='login'),
    path('administrative/dashboard/', views.administrative_dashboard, name='administrative_dashboard'),
    path('technician/dashboard/', views.technician_dashboard, name='technician_dashboard'),
    path('unknown_role/', views.unknown_role_dashboard, name='unknown_role_dashboard'),
    path('registrar-paciente/', registrar_paciente, name='registrar_paciente'),
    path('editar_paciente/<int:paciente_id>/', views.editar_paciente, name='editar_paciente'),
    path('eliminar-paciente/<int:paciente_id>/', eliminar_paciente, name='eliminar_paciente'),
    path('agregar-examenes-paciente/<int:paciente_id>/', views.agregar_examenes_paciente, name='agregar_examenes_paciente'),
    path('mostrar-resultados-examenes/', views.mostrar_resultados_examenes, name='mostrar_resultados_examenes'),
    path('ver-pedidos-pendientes/', views.ver_pedidos_pendientes, name='ver_pedidos_pendientes'),
    path('agregar-resultados-examenes/', views.agregar_resultados_examenes, name='agregar_resultados_examenes'),
    path('ingresar-resultados-examenes/', views.ingresar_resultados_examenes, name='ingresar_resultados_examenes'),
]

home/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from django.db import models

class Administrativo(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    # Agrega más campos según sea necesario

    def __str__(self):
        return str(self.usuario)

class Tecnico(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    # Agrega más campos según sea necesario

    def __str__(self):
        return str(self.usuario)
    
class Paciente(models.Model):
    cedula = models.CharField(max_length=10, validators=[MaxLengthValidator(10)], null=True, blank=True)
    nombre = models.CharField(max_length=100, null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)
    direccion = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.cedula
    
class Examen_disponible(models.Model):
    nombre_examen = models.CharField(max_length=100)
    unidad = models.CharField(max_length=10, null=True, blank=True)
    area = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.nombre_examen
    
class Pedido_examen(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, related_name='pedidos_examenes')
    fecha = models.DateField(auto_now_add=True)
    pendiente = models.BooleanField(default=True)  # Nuevo campo para indicar si el pedido está pendiente o procesado
    examenes_disponibles = models.ManyToManyField(Examen_disponible, related_name='pedidos_examenes')  # Relación muchos a muchos con Examen_disponible

    def __str__(self):
        return f"Pedido para {self.paciente} - {self.fecha}"
    
class Resultado_examen(models.Model):
    pedido_examen = models.ForeignKey(Pedido_examen, on_delete=models.CASCADE, related_name='resultados_examenes')
    nombre_examen = models.ForeignKey(Examen_disponible, on_delete=models.CASCADE)
    valor_resultado = models.FloatField(null=True, blank=True)
    rango = models.CharField(max_length=25, null=True, blank=True)

    def __str__(self):
        return f"Resultado para {self.pedido_examen} - {self.pedido_examen}"
    


    

home/forms.py
from django import forms
from .models import Paciente , Resultado_examen, Examen_disponible, Pedido_examen

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['cedula','nombre', 'edad', 'direccion']


class ResultadoExamenForm(forms.ModelForm):
    class Meta:
        model = Resultado_examen
        fields = ['valor_resultado', 'rango']

class SeleccionarExamenesForm(forms.Form):
    def __init__(self, *args, **kwargs):
        examenes = kwargs.pop('examenes')
        super(SeleccionarExamenesForm, self).__init__(*args, **kwargs)
        for examen in examenes:
            self.fields[str(examen.id)] = forms.BooleanField(label=examen.nombre_examen, required=False)

class PedidoExamenForm(forms.ModelForm):
    class Meta:
        model = Pedido_examen
        fields = ['paciente']

home/views.py
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .models import Paciente, Examen_disponible
from .forms import PacienteForm, SeleccionarExamenesForm, ResultadoExamenForm, Pedido_examen

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.groups.filter(name='Administrativo').exists():
                return redirect('administrative_dashboard')
            elif user.groups.filter(name='Tecnico').exists():
                return redirect('technician_dashboard')
            else:
                return redirect('unknown_role_dashboard')
        else:
            messages.error(request, 'Nombre de usuario o contraseña incorrectos.')
    return render(request, 'login.html')

def administrative_dashboard(request):
    pacientes = Paciente.objects.all()
    return render(request, 'administrative_dashboard.html', {'pacientes': pacientes})

def technician_dashboard(request):
    # Obtener todos los pacientes de la base de datos
    pacientes = Paciente.objects.all()
    # Renderizar la plantilla y pasar los pacientes como contexto
    return render(request, 'technician_dashboard.html', {'pacientes': pacientes})

def unknown_role_dashboard(request):
    return render(request, 'unknown_role_dashboard.html')

def registrar_paciente(request):
    if request.method == 'POST':
        form = PacienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('administrative_dashboard')
    else:
        return redirect('administrative_dashboard')  # Redirigir a otra página

def editar_paciente(request, paciente_id):
    paciente = get_object_or_404(Paciente, pk=paciente_id)
    if request.method == 'POST':
        form = PacienteForm(request.POST, instance=paciente)
        if form.is_valid():
            form.save()
            return redirect('administrative_dashboard')
    else:
        form = PacienteForm(instance=paciente)
    return render(request, 'editar_paciente.html', {'form': form, 'paciente': paciente})


def eliminar_paciente(request, paciente_id):
    # Obtener el paciente por su ID
    paciente = get_object_or_404(Paciente, pk=paciente_id)
    if request.method == 'POST':
        # Eliminar el paciente de la base de datos si se confirma la acción
        paciente.delete()
        # Redirigir al usuario de vuelta al dashboard administrativo
        return redirect('administrative_dashboard')
    # Si no es una solicitud POST, mostrar una página de confirmación
    return render(request, 'confirmar_eliminacion_paciente.html', {'paciente': paciente})

def agregar_examenes_paciente(request, paciente_id):
    paciente = get_object_or_404(Paciente, pk=paciente_id)
    examenes_disponibles = Examen_disponible.objects.all()

    if request.method == 'POST':
        form = SeleccionarExamenesForm(request.POST, examenes=examenes_disponibles)
        if form.is_valid():
            examenes_seleccionados_ids = [int(id) for id, seleccionado in form.cleaned_data.items() if seleccionado]
            # Crear un nuevo pedido de examen para el paciente
            pedido_examen = Pedido_examen.objects.create(paciente=paciente)
            # Asociar los exámenes seleccionados al pedido de examen
            pedido_examen.examenes_disponibles.add(*examenes_seleccionados_ids)
            messages.success(request, '¡Exámenes agregados con éxito!')
            # Redirigir al dashboard administrativo
            return redirect('administrative_dashboard')
    else:
        form = SeleccionarExamenesForm(examenes=examenes_disponibles)

    return render(request, 'agregar_examenes_paciente.html', {'paciente': paciente, 'form': form})

def pedidos_pendientes(request):
    # Obtener los pedidos pendientes
    pedidos_pendientes = Pedido_examen.objects.filter(resultados__isnull=True)
    return render(request, 'pedidos_pendientes.html', {'pedidos_pendientes': pedidos_pendientes})

def mostrar_resultados_examenes(request):
    # Aquí puedes agregar la lógica para obtener los resultados de los exámenes
    # desde la base de datos o cualquier otra fuente de datos.
    # Por ahora, simplemente renderizaremos una plantilla de resultados vacía.
    return render(request, 'mostrar_resultados_examenes.html')

def ver_pedidos_pendientes(request):
    # Agrega la lógica necesaria para obtener los pedidos pendientes
    # desde la base de datos o cualquier otra fuente de datos.
    # Por ahora, simplemente renderizaremos una plantilla vacía.
    return render(request, 'ver_pedidos_pendientes.html')

def agregar_resultados_examenes(request):
    # Lógica para obtener los datos necesarios para el formulario de resultados de exámenes
    # Por ejemplo, puedes obtener la lista de pacientes con pedidos pendientes de exámenes
    # y los detalles de los exámenes solicitados para cada paciente.
    
    # Aquí iría tu lógica para obtener los datos necesarios
    # patients_with_pending_orders = ...

    # Luego, pasas los datos al template
    return render(request, 'agregar_resultados_examenes.html', {
        # Puedes pasar los datos necesarios al template como contexto
        # 'patients_with_pending_orders': patients_with_pending_orders,
    })

def ingresar_resultados_examenes(request, pedido_id):
    pedido = get_object_or_404(Pedido_examen, pk=pedido_id)
    
    if request.method == 'POST':
        form = ResultadoExamenForm(request.POST)
        if form.is_valid():
            resultado_examen = form.save(commit=False)
            resultado_examen.pedido = pedido
            resultado_examen.save()
            return redirect('detalle_pedido', pedido_id=pedido_id)  # Redirige a la página de detalles del pedido o donde desees
    else:
        form = ResultadoExamenForm()
    
    return render(request, 'ingresar_resultados.html', {'form': form, 'pedido': pedido})

home/templates/administrative_dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Administrative Dashboard</title>
    <!-- Agrega el enlace al CSS de Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <style>
      /* Estilos anteriores */
      table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
      }

      th,
      td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      /* Estilos adicionales */
      .form-container label {
        display: inline-block;
        width: 120px; /* Ajusta el ancho según sea necesario */
        text-align: right;
        margin-right: 10px;
      }

      .form-container input {
        width: 200px; /* Ajusta el ancho según sea necesario */
      }

      /* Estilos para los botones de iconos */
      .icon-button {
        background-color: transparent;
        border: none;
        cursor: pointer;
        outline: none;
        margin-right: 5px; /* Espacio entre los botones */
        position: relative;
      }

      .icon-button:hover {
        opacity: 0.7;
      }

      /* Estilos para el texto que se muestra al pasar el mouse sobre el botón */
      .icon-button:hover::after {
        content: attr(data-title);
        position: absolute;
        top: -25px;
        left: 50%;
        transform: translateX(-50%);
        background-color: #333;
        color: #fff;
        padding: 5px 10px;
        border-radius: 5px;
        font-size: 12px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>Bienvenido, {{ user.username }}!</h2>
      <p>Este es el Panel Administrativo.</p>

      <!-- Agregar el botón para mostrar el formulario de ingreso de pacientes -->
      <button onclick="toggleForm()">Agregar Paciente</button>

      <!-- Formulario de ingreso de pacientes -->
      <div id="form-container" class="form-container" style="display: none">
        <h3>Agregar Nuevo Paciente</h3>
        <form method="post" action="{% url 'registrar_paciente' %}">
          {% csrf_token %}
          <!-- Campos del formulario de ingreso de pacientes -->
          <label for="id_cedula">Cédula:</label>
          <input
            type="text"
            name="cedula"
            id="id_cedula"
            maxlength="10"
            required
          /><br />
          <label for="id_nombre">Nombre:</label>
          <input type="text" name="nombre" id="id_nombre" required /><br />
          <label for="id_edad">Edad:</label>
          <input type="number" name="edad" id="id_edad" required /><br />
          <label for="id_direccion">Dirección:</label>
          <input
            type="text"
            name="direccion"
            id="id_direccion"
            required
          /><br />
          <!-- Botón de enviar formulario sin icono -->
          <button type="submit">Guardar</button>
        </form>
      </div>

      <!-- Agregar el filtro de búsqueda -->
      <div id="search-container">
        <h3>Buscar Paciente</h3>
        <input
          type="text"
          id="search-input"
          placeholder="Buscar por cédula..."
          onkeyup="searchPatients()"
        />
      </div>

      <!-- Mostrar la lista de pacientes (solo los últimos 5) -->
      <h3>Listado de Últimos 5 Pacientes</h3>
      <table id="patient-table">
        <thead>
          <tr>
            <th>Cédula</th>
            <th>Nombre</th>
            <th>Edad</th>
            <th>Dirección</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for paciente in pacientes %} {% if paciente.id is not None %}
          <tr>
            <td>{{ paciente.cedula }}</td>
            <td>{{ paciente.nombre }}</td>
            <td>{{ paciente.edad }}</td>
            <td>{{ paciente.direccion }}</td>
            <td>
              <!-- Agregar botones de editar, eliminar, agregar exámenes, ver pedidos pendientes y ver resultados de exámenes -->
              <a
                href="{% url 'editar_paciente' paciente.id %}"
                class="icon-button"
                data-title="Editar Paciente"
              >
                <i class="fas fa-edit"></i>
              </a>
              <a
                href="{% url 'eliminar_paciente' paciente.id %}"
                class="icon-button"
                data-title="Eliminar Paciente"
              >
                <i class="fas fa-trash-alt"></i>
              </a>
              <a
                href="{% url 'agregar_examenes_paciente' paciente.id %}"
                class="icon-button"
                data-title="Agregar Exámenes"
              >
                <i class="fas fa-plus"></i>
              </a>
              <a
                href="{% url 'ver_pedidos_pendientes' %}"
                class="icon-button"
                data-title="Pedidos Pendientes"
              >
                <i class="fas fa-file-alt"></i>
              </a>
              <a
                href="{% url 'mostrar_resultados_examenes' %}"
                class="icon-button"
                data-title="Resultados de Exámenes"
              >
                <i class="fas fa-poll"></i>
              </a>
            </td>
          </tr>
          {% endif %} {% endfor %}
        </tbody>
      </table>
    </div>

    <script>
      function toggleForm() {
        var formContainer = document.getElementById("form-container");
        formContainer.style.display =
          formContainer.style.display == "none" ? "block" : "none";
      }
    </script>

    <!-- Función JavaScript para filtrar pacientes -->
    <script>
      function searchPatients() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("search-input");
        filter = input.value.toUpperCase();
        table = document.getElementById("patient-table");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
          td = tr[i].getElementsByTagName("td")[0]; // Buscar en la primera columna (cedula)
          if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
              tr[i].style.display = "";
            } else {
              tr[i].style.display = "none";
            }
          }
        }
      }
    </script>
  </body>
</html>

home/templates/agregar_examenes_paciente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agregar Exámenes al Paciente</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      .container {
        max-width: 600px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }

      h1 {
        text-align: center;
        color: #333;
      }

      form {
        margin-top: 20px;
      }

      .button {
        background-color: #007bff;
        border: none;
        color: #fff;
        padding: 12px 24px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }

      .button:hover {
        background-color: #0056b3;
      }

      .button-cancel {
        background-color: #dc3545;
      }

      .button-container {
        text-align: center;
        margin-top: 20px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Agregar Exámenes al Paciente</h1>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div class="button-container">
          <button type="submit" class="button">Guardar</button>
          <a
            href="{% url 'administrative_dashboard' %}"
            class="button button-cancel"
            >Cancelar</a
          >
        </div>
      </form>
    </div>
  </body>
</html>

home/templates/agregar_resultados_examenes.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ingresar Resultados</title>
    <!-- Agrega cualquier estilo adicional aquí -->
    <style>
      /* Estilos para la tabla */
      table {
        border-collapse: collapse;
        width: 100%;
      }
      th,
      td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }
      th {
        background-color: #f2f2f2;
      }
      /* Estilos para los campos de entrada */
      .result-input {
        width: 100px; /* Ajusta el ancho según sea necesario */
      }
    </style>
  </head>
  <body>
    <h1>Ingresar Resultados de Examen</h1>
    <h2>Pedido para: {{ pedido.paciente }}</h2>
    <!-- Mostrar los datos del pedido en una tabla -->
    <table>
      <thead>
        <tr>
          <th>Examen</th>
          <th>Valores de Referencia</th>
          <th>Valor Resultado</th>
          <th>Rango</th>
        </tr>
      </thead>
      <tbody>
        {% for examen in pedido.paciente.pedidos_examenes.all %}
        <tr>
          <td>{{ examen }}</td>
          <td>{{ examen.valores_referencia }}</td>
          <td>
            <input
              type="text"
              name="valor_resultado_{{ examen.id }}"
              class="result-input"
            />
          </td>
          <td>
            <input
              type="text"
              name="rango_{{ examen.id }}"
              class="result-input"
            />
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <form method="post">
      {% csrf_token %}
      <button type="submit">Guardar Resultados</button>
    </form>
  </body>
</html>

home/templates/confirmar_eliminacion_paciente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Confirmar Eliminación de Paciente</title>
  </head>
  <body>
    <h2>Confirmar Eliminación de Paciente</h2>
    <p>
      ¿Está seguro de que desea eliminar al paciente "{{ paciente.nombre }}"?
    </p>
    <form method="post">
      {% csrf_token %}
      <input type="submit" value="Sí, Eliminar" />
      <button onclick="cancelarEliminacion()">Cancelar</button>
    </form>

    <script>
      function cancelarEliminacion() {
        window.history.back(); // Regresar a la página anterior
      }
    </script>
  </body>
</html>

home/templates/editar_paciente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Editar Paciente</title>
    <!-- Agrega el enlace al CSS de Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <style>
      /* Estilos generales */
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
      }

      .container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }

      h2 {
        margin-top: 0;
        font-size: 24px;
        color: #333;
      }

      form {
        margin-top: 20px;
      }

      .form-group {
        margin-bottom: 20px;
      }

      label {
        display: block;
        font-weight: bold;
        margin-bottom: 5px;
      }

      input[type="text"],
      input[type="number"] {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 5px;
      }

      button[type="submit"],
      button[type="button"] {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
      }

      button[type="submit"]:hover,
      button[type="button"]:hover {
        background-color: #0056b3;
      }

      .cancel-button {
        background-color: #dc3545;
        margin-right: 10px;
        width: 200px; /* Mismo ancho que el botón de guardar pacientes */
      }

      .cancel-button:hover {
        background-color: #bd2130;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>Editar Paciente</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_cedula">Cédula:</label>
          <input
            type="text"
            name="cedula"
            id="id_cedula"
            value="{{ paciente.cedula }}"
            required
          />
        </div>
        <div class="form-group">
          <label for="id_nombre">Nombre:</label>
          <input
            type="text"
            name="nombre"
            id="id_nombre"
            value="{{ paciente.nombre }}"
            required
          />
        </div>
        <div class="form-group">
          <label for="id_edad">Edad:</label>
          <input
            type="number"
            name="edad"
            id="id_edad"
            value="{{ paciente.edad }}"
            required
          />
        </div>
        <div class="form-group">
          <label for="id_direccion">Dirección:</label>
          <input
            type="text"
            name="direccion"
            id="id_direccion"
            value="{{ paciente.direccion }}"
            required
          />
        </div>
        <button type="submit">Guardar Cambios</button>
        <button type="button" class="cancel-button" onclick="cancelEdit()">
          Cancelar
        </button>
      </form>
    </div>

    <script>
      function cancelEdit() {
        // Implementa aquí la lógica para cancelar la edición del paciente, si es necesario
        // Por ejemplo, puedes redirigir al usuario a otra página o mostrar un mensaje de confirmación
        // En este ejemplo, simplemente redirigiremos al usuario al dashboard administrativo
        window.location.href = "{% url 'administrative_dashboard' %}";
      }
    </script>
  </body>
</html>

home/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }
      .container {
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      h2 {
        text-align: center;
        margin-bottom: 20px;
      }
      form {
        max-width: 300px;
        margin: 0 auto;
      }
      input[type="text"],
      input[type="password"],
      button[type="submit"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
      }
      button[type="submit"] {
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
      }
      button[type="submit"]:hover {
        background-color: #0056b3;
      }
      p.error {
        color: #dc3545;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>Login</h2>
      <form method="post">
        {% csrf_token %}
        <input
          type="text"
          name="username"
          placeholder="Username"
          required
        /><br />
        <input
          type="password"
          name="password"
          placeholder="Password"
          required
        /><br />
        <button type="submit">Login</button>
      </form>
      {% if error %}
      <p class="error">{{ error }}</p>
      {% endif %}
      <!-- Enlace para acceder al panel de administración -->
      <p>
        ¿Eres administrador?
        <a href="{% url 'admin:index' %}">Accede al panel de administración</a>
      </p>
    </div>
  </body>
</html>

home/templates/mostrar_resultados_examenes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mostar Resultados Examanes</title>
    <!-- Agrega cualquier estilo adicional aquí -->
  </head>
  <body>
    <h1>Mostar Resultados Examanes</h1>
    <!-- Aquí puedes agregar la tabla u otro elemento para mostrar los pedidos pendientes -->
  </body>
</html>

home/templates/unknown_role_dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Error - Unknown Role</title>
  </head>
  <body>
    <h2>Error - Unknown Role</h2>
    <p>You do not have access to this dashboard.</p>
    <!-- Add additional message or instructions here -->
  </body>
</html>

home/templates/ver_pedidos_pendientes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ver Pedidos Pendientes</title>
    <!-- Agrega cualquier estilo adicional aquí -->
  </head>
  <body>
    <h1>Pedidos Pendientes</h1>
    <table>
      <thead>
        <tr>
          <th>Número de Pedido</th>
          <th>Nombre del Paciente</th>
          <th>Cédula del Paciente</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for pedido in pedidos %}
        <tr>
          <td>{{ pedido.id }}</td>
          <!-- Asumiendo que id es el número de pedido -->
          <td>{{ pedido.paciente.nombre }}</td>
          <td>{{ pedido.paciente.cedula }}</td>
          <td>
            <a href="{% url 'ingresar_resultados' pedido.id %}" class="btn"
              >Ingresar Resultados</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>